TEX=pdflatex
BIBTEX=bibtex
MAIN=main

TEXSRC=$(wildcard *.tex sections/*.tex figures/*.tex)
PDF=$(MAIN).pdf
REFACTORED_PDF=$(MAIN)_refactored.pdf

all: $(PDF)

all_refactored: $(REFACTORED_PDF)

ifneq (,$(wildcard .env))
  include .env
  export
endif

# Define the source Markdown file
MD_SOURCE=$(MC_SOURCE)

$(PDF): $(TEXSRC) .author_info.tex bibliography.bib
	@echo "Validating Markdown structure..."
	@python3 validate_markdown_structure.py $(MD_SOURCE) --skip-hierarchy-check > /tmp/md_validation.log || (cat /tmp/md_validation.log && exit 1)
	@CLEANED_MD=$$(tail -n 1 /tmp/md_validation.log); \
	echo "Using cleaned Markdown: $$CLEANED_MD"; \
	python3 auto_transcribe_md_to_tex.py $$CLEANED_MD
	python3 auto_increment_version.py
	$(TEX) $(MAIN).tex
	$(BIBTEX) $(MAIN) || true
	$(TEX) $(MAIN).tex
	$(TEX) $(MAIN).tex

$(REFACTORED_PDF): $(TEXSRC) .author_info.tex bibliography.bib
	@echo "Validating Markdown structure (for refactored build)..."
	@python3 validate_markdown_structure.py $(MD_SOURCE) --skip-hierarchy-check > /tmp/md_validation_refactored.log || (cat /tmp/md_validation_refactored.log && exit 1)
	@CLEANED_MD_REFACTORED=$$(tail -n 1 /tmp/md_validation_refactored.log); \
	echo "Using cleaned Markdown (for refactored build): $$CLEANED_MD_REFACTORED"; \
	python3 refactored_md_to_tex_converter.py $$CLEANED_MD_REFACTORED
	python3 auto_increment_version.py # Consider if versioning should be separate or if it affects the same version file
	$(TEX) $(MAIN).tex # This will compile main.tex, which includes sections generated by the script
	$(BIBTEX) $(MAIN) || true
	$(TEX) $(MAIN).tex
	$(TEX) $(MAIN).tex

clean:
	rm -f *.aux *.bbl *.blg *.log *.out *.toc *.lof *.lot *.fls *.fdb_latexmk $(PDF) $(REFACTORED_PDF)